/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package moduldua;

import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Satu extends javax.swing.JFrame {
    public int JamKerja, TarifPerjam, GajiBruto, JamLembur, gajilembur, Pajak, GajiBersih;
    /**
     * Creates new form Satu
     */
    public Satu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbJumlahJam = new javax.swing.JLabel();
        lbTarif = new javax.swing.JLabel();
        btGajiBruto = new javax.swing.JButton();
        lbGajiBruto = new javax.swing.JLabel();
        btGajiBersih = new javax.swing.JButton();
        lbGajiBersih = new javax.swing.JLabel();
        tfJumlahJam = new javax.swing.JTextField();
        tfTarif = new javax.swing.JTextField();
        tfGajiBruto = new javax.swing.JTextField();
        tfGajiBersih = new javax.swing.JTextField();
        btKeluar = new javax.swing.JButton();
        btReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        lbJumlahJam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbJumlahJam.setForeground(new java.awt.Color(255, 255, 255));
        lbJumlahJam.setText("Jumlah Jam Kerja 1 Minggu       :");

        lbTarif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTarif.setForeground(new java.awt.Color(255, 255, 255));
        lbTarif.setText("Tarif Per-jam                                  :");

        btGajiBruto.setText("Hitung Gaji Bruto");
        btGajiBruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGajiBrutoActionPerformed(evt);
            }
        });

        lbGajiBruto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGajiBruto.setForeground(new java.awt.Color(255, 255, 255));
        lbGajiBruto.setText("Gaji Bruto                                        :");

        btGajiBersih.setText("Hitung Gaji Bersih");
        btGajiBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGajiBersihActionPerformed(evt);
            }
        });

        lbGajiBersih.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGajiBersih.setForeground(new java.awt.Color(255, 255, 255));
        lbGajiBersih.setText("Gaji Bersih                                       :");

        tfTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTarifActionPerformed(evt);
            }
        });

        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        btReset.setText("Reset");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btGajiBruto)
                            .addComponent(lbGajiBruto)))
                    .addComponent(btGajiBersih)
                    .addComponent(lbGajiBersih)
                    .addComponent(lbJumlahJam, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btKeluar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfGajiBruto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(tfGajiBersih)
                        .addComponent(tfTarif)
                        .addComponent(tfJumlahJam)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbJumlahJam)
                    .addComponent(tfJumlahJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTarif)
                    .addComponent(tfTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGajiBruto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGajiBruto)
                    .addComponent(tfGajiBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGajiBersih)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGajiBersih)
                    .addComponent(tfGajiBersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKeluar)
                    .addComponent(btReset))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGajiBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGajiBersihActionPerformed
        if (JamKerja <= 0 || TarifPerjam <=0){
            JOptionPane.showMessageDialog(this, "Masukkan Jumlah Yang Benar");
            return;
        }
        Pajak = (int)(0.1 * GajiBruto);
        GajiBersih = GajiBruto - Pajak;
        tfGajiBersih.setText(String.valueOf(GajiBersih));
    }//GEN-LAST:event_btGajiBersihActionPerformed

    private void btGajiBrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGajiBrutoActionPerformed
        if (JamKerja <= 0 || TarifPerjam <=0){
            JOptionPane.showMessageDialog(this, "Masukkan Jumlah Yang Benar");
            return;
        }
            
        JamKerja = Integer.parseInt(tfJumlahJam.getText());
        TarifPerjam = Integer.parseInt(tfTarif.getText());
        if (JamKerja <= 40){
            GajiBruto = JamKerja * TarifPerjam;
        }
        else {
            JamLembur = JamKerja - 40;
            gajilembur = (int)(JamLembur * (TarifPerjam * 1.5));
            GajiBruto = 40 * TarifPerjam + gajilembur;
        }
        tfGajiBruto.setText(String.valueOf(GajiBruto));
    }//GEN-LAST:event_btGajiBrutoActionPerformed

    private void tfTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTarifActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        tfJumlahJam.setText("");
        tfTarif.setText("");
        tfGajiBruto.setText("");
        tfGajiBersih.setText("");
        
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Satu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Satu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGajiBersih;
    private javax.swing.JButton btGajiBruto;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbGajiBersih;
    private javax.swing.JLabel lbGajiBruto;
    private javax.swing.JLabel lbJumlahJam;
    private javax.swing.JLabel lbTarif;
    private javax.swing.JTextField tfGajiBersih;
    private javax.swing.JTextField tfGajiBruto;
    private javax.swing.JTextField tfJumlahJam;
    private javax.swing.JTextField tfTarif;
    // End of variables declaration//GEN-END:variables
}
